version: "3.7"

services:
  peripheral-manager-modbus:
    build: .
    restart: on-failure
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=nuvla.io
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    network_mode: host

