version: "3.7"

services:
  peripheral-manager-modbus:
    build: .
    restart: on-failure
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production

